#define DEVICE_ID "1"

#define IN_TOPIC "/state_in"
#define OUT_TOPIC "/state_out"
#define STATUS_TOPIC "/status_out"
#define TEMPERATURE_TOPIC "/temperature_in"
#define THERMOSTAT_TOPIC "/thermostat_in"
#define DOOR_TOPIC "/door_in"
#define AVAILABLE_MODES_TOPIC "available_modes_in"
#define SIGNAL_TOPIC "/signal_out"
#define IP_ADDRESS_TOPIC "/ip_address_out"
#define CAPABILITIES_TOPIC "/capabilities_out"
#define TOPICS_ROOT "midea/hvac/"

#define MY_MQTT_IN_TOPIC TOPICS_ROOT DEVICE_ID IN_TOPIC
#define MY_MQTT_OUT_TOPIC TOPICS_ROOT DEVICE_ID OUT_TOPIC
#define MY_MQTT_STATUS_TOPIC TOPICS_ROOT DEVICE_ID STATUS_TOPIC
#define MY_MQTT_TEMPERATURE_TOPIC TOPICS_ROOT DEVICE_ID TEMPERATURE_TOPIC
#define MY_MQTT_THERMOSTAT_TOPIC TOPICS_ROOT DEVICE_ID THERMOSTAT_TOPIC
#define MY_MQTT_DOOR_TOPIC TOPICS_ROOT DEVICE_ID DOOR_TOPIC
#define MY_MQTT_AVAILABLE_MODES_TOPIC TOPICS_ROOT AVAILABLE_MODES_TOPIC
#define MY_MQTT_SIGNAL_TOPIC TOPICS_ROOT DEVICE_ID SIGNAL_TOPIC
#define MY_MQTT_IP_ADDRESS_TOPIC TOPICS_ROOT DEVICE_ID IP_ADDRESS_TOPIC
#define MY_MQTT_CAPABILITIES_TOPIC TOPICS_ROOT DEVICE_ID CAPABILITIES_TOPIC
#define MQTT_BUFFER_LENGTH 500
#define WIFI_CONNECTION_TIMEOUT 30000
#define MQTT_RETRY_TIME 1000
#define MQTT_MAX_RETRIES 30
#define MQTT_STATUS_UPDATE_TIME_MS 60000